[SRBT-157] Better QR code for share dialog
MySorbet/sorbet-app pull request #111
Opened 2024-10-14 19:38 UTC by audreyostrom

# [SRBT-157] Better QR code for share dialog

**Changes**

- Added `qr-code-styling` package to have a customized QR code that's more in-line with Sorbet's branding. This was the settled upon design that is stylish, while still consistently scannable.
- Fixed a hydration error that's cause by opening the share dialog (`Warning: In HTML, <button> cannot be a descendant of <button>. This will cause a hydration error.`) by converting removing a nested button in `share-on-socials.tsx`(
- Fixed `Warning: React does not recognize the `hideDefaultCloseButton` prop on a DOM element.` in the dialog component by destructuring hideDefaultCloseButton from the props in the DialogContent component.

# Screenshots
![Screenshot 2024-10-14 at 12 33 10 PM](https://github.com/user-attachments/assets/cfc51ca9-c0dc-467d-b4b6-794e24d940f4)

2024-10-15 16:32 UTC, Cutaiar requested changes

2024-10-15 16:32 UTC, Cutaiar commented on src/components/profile/share/share-profile-dialog.tsx
> +            height: activeView === 'ShareYourProfile' ? '390px' : contentHeight,
Why is this needed? Seems like it is adding an extra height transition when the dialog first opens.

2024-10-15 16:32 UTC, Cutaiar commented on src/components/ui/dialog.tsx
> +  // const {hideDefaultCloseButton} = props
Please remove this commented line

2024-10-15 16:32 UTC, Cutaiar commented on src/hooks/profile/useGenerateQRCode.ts
> +      width: 300,
Why not `import QRCodeStyling, { type Options } from 'qr-code-styling';` at the top?

2024-10-15 16:32 UTC, Cutaiar commented on src/hooks/profile/useGenerateQRCode.ts
> +      width: 300,
```suggestion
    const qrOptions: Options = {
```

to type this object as the constructor expects

2024-10-15 16:32 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
> +  const ref = useRef<HTMLDivElement>(null);
Rather than use state and effects to keep the qr code updated with the url (which never changes). Why not make the url an argument to the `useGenenerateQRCode` hook and move the effect inside (if it is still even needed)? This keeps the implementation details of the QR code generation out of the UI code here.

2024-10-15 16:32 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
> +  const handleDownload = (fileExt: 'svg' | 'png') => {
See my comment regarding the `useGenerateQRCode` above -- this could also be a fn returned by the hook to further isolate implementation detials from UI. so something like: 

```ts
const {qrCode, downloadQRCode} = useGenerateQRCode(url)
```

What do you think?

2024-10-15 16:32 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
>  import { ViewProps } from '../share-profile-dialog';
You can use eslint to autoorganize these imports. Use `cmd .`.

2024-10-15 16:32 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
> +  const qrCode = useGenerateQRCode();
Would consider calling this ref `qrCodeRef` or something similar to describe what it it used for.

2024-10-15 16:32 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
> +            {!ref ? <Spinner /> : <div ref={ref} />}
I thought we would be able to make the rendering of the QR code syncronous by using a library rather than an API. From my testing, looks like there is still a loading period. If this is unavoidable, would prefer it load with a shadcn skeleton of the same height (or at least worth a try to see if it looks more polished)
https://ui.shadcn.com/docs/components/skeleton

2024-10-15 16:33 UTC, Cutaiar commented
<img width="459" alt="image" src="https://github.com/user-attachments/assets/cec27dbc-abba-49d7-ba70-3c00cd96699d">
On my machine, the display QR code has artifacts around the edges (looks low res and chunky). Is there a way to render this in higher resolution, as an svg, or another way that fixes this?

2024-10-15 16:34 UTC, Cutaiar commented
Nice work Audrey, left some comments. Please message me if you have any questions :)

2024-10-15 17:18 UTC, audreyostrom commented on public/svg/large-logo.svg
I remember when I was testing it, it looks compressed to me. After switching it the `logo.svg` again, I think my eyes might've been the issue in this case since it's an SVG to begin with.

2024-10-15 19:03 UTC, audreyostrom commented on src/hooks/profile/useGenerateQRCode.ts
> +      width: 300,
Fixed, and now importing is more standard.  Prior to an [update](https://github.com/kozakdenys/qr-code-styling/pull/64) to `qr-code-styling`, [this](https://github.com/kozakdenys/qr-code-styling/issues/38) was the way to use this library with NextJS projects to avoid `Reference Error: self is not defined` errors.

2024-10-15 19:03 UTC, audreyostrom commented on src/hooks/profile/useGenerateQRCode.ts
> +      width: 300,
Fixed, and also adjusted width and height back to 256 like the original QR code.

2024-10-15 20:56 UTC, audreyostrom commented on src/components/profile/share/views/share-on-socials.tsx
> +  const handleDownload = (fileExt: 'svg' | 'png') => {
That would make this simpler/nicer, so I'll go ahead and do that!

2024-10-15 21:09 UTC, audreyostrom commented on src/components/profile/share/share-profile-dialog.tsx
> +            height: activeView === 'ShareYourProfile' ? '390px' : contentHeight,
It's related to me changing the `Button` on Share Your Profile to a `div` (to fix a hydration error that I got when I opened the page regarding nested buttons). It messes up the height of the page and causes it to get cut off like so:
![Screenshot 2024-10-15 at 10 32 12 AM](https://github.com/user-attachments/assets/b6c33bab-c9da-4007-8449-6300df10d2f9)

It can be fixed and kept to 372 px by styling the div like a button:
<img width="566" alt="Screenshot 2024-10-15 at 2 05 16 PM" src="https://github.com/user-attachments/assets/daca7f72-3480-425a-b2fc-3069434c498d">

But I wasn't sure if styling like this broke any codebase standards there might be, so I changed the height initially to 390px instead. 

I can either ignore the hydration error or do one of the two ways listed – but if there's an better solution let me know! @Cutaiar

2024-10-15 21:40 UTC, audreyostrom commented
Regarding the fuzzy picture on your end @Cutaiar, I changed the QR code to be rendered as an SVG instead using an HTML canvas. I think that removed a lot of artifacts on my end when I viewed it.

2024-10-15 22:03 UTC, audreyostrom commented on src/components/profile/share/views/share-on-socials.tsx
> +            {!ref ? <Spinner /> : <div ref={ref} />}
I re-did it so there's a Skeleton component instead. There might be some delay in the QR code actually displaying due to the animations on the page or delay in images loading in general, but I'm unsure if that's entirely removable since testing with other static image elements also had the same delay.

2024-10-15 22:07 UTC, audreyostrom commented on src/styles/globals.css
I didn't end up editing this file, but the linting rules applied when I saved the file undoing my changes. Hence, why the spacing is different.

2024-10-16 03:57 UTC, Cutaiar requested changes
Here, I just moved state management into the useGenerateQRCode hook and fixed imports by running eslint auto fix.

2024-10-16 03:57 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
> +import { Skeleton } from '@/components/ui/skeleton';
```suggestion
import { CheckCircle, Download01 } from '@untitled-ui/icons-react';
import { useEffect, useRef, useState } from 'react';

import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { useGenerateQRCode } from '@/hooks/profile/useGenerateQRCode';

import { Body, Header, ShareLink } from '../components';
import { ViewProps } from '../share-profile-dialog';
```

2024-10-16 04:03 UTC, Cutaiar commented on src/components/profile/share/share-profile-dialog.tsx
> +            height: activeView === 'ShareYourProfile' ? '390px' : contentHeight,
No broken standards :). Thanks for fixing existing errors, I'm mostly concerned about the extra height transition the change added. Looks like it has gone away with this new change so this is good.

2024-10-16 04:08 UTC, Cutaiar commented
This is getting close to going in, left a few more suggestions.

2024-10-16 14:43 UTC, audreyostrom commented on src/components/profile/share/views/share-on-socials.tsx
> +import { Skeleton } from '@/components/ui/skeleton';
Sounds good, I just moved everything and linted the files I edited like you suggested.

2024-10-16 22:12 UTC, Cutaiar commented on src/components/profile/share/views/share-on-socials.tsx
> +import { Skeleton } from '@/components/ui/skeleton';
Ah I see. In the diff I just moved the qr code state, not the isCopied bits. But whichever you prefer.

2024-10-16 22:13 UTC, Cutaiar approved these changes

2024-10-17 17:44 UTC, audreyostrom commented on src/components/profile/share/views/share-on-socials.tsx
> +import { Skeleton } from '@/components/ui/skeleton';
Ah, I think the suggestion preview might've not have displayed that on my end (or maybe I missed it entirely). I brought back the isCopied bits and the downloadQRCode function so `useGenerateQRCode` only generates the QR code.

2024-10-17 18:04 UTC, merged