[SRBT-201] Dragging and dropping images should upload them as widgets
MySorbet/sorbet-app pull request #112
Opened 2024-10-15 00:54 UTC by audreyostrom

# [SRBT-201] Drag and drop images in profile dashboard

**Changes**

- You can now upload images to your profile by dragging some png, svg, jpg, or gif directly from your files
- Refactored the Widget Grid component (widget-grid.tsx) into smaller components (file-drop-area.tsx) and hooks (useWidgetGrid.ts) to keep the original component more compact/readable.

# Screenshots

https://github.com/user-attachments/assets/1b4c8c00-80c7-4c5f-b600-b447dee1f4ea

2024-10-15 16:49 UTC, Cutaiar commented on src/hooks/profile/useWidgetGrid.ts
We inherited the WidgetGrid component -- agree that is a mess with all the of effects and hook calls (some of which i think are not even needed). And agree that some refactoring would be good. But I don't think pulling everything out into one hook makes it much clearer what's going on. Since you will be working in this area, I'm fine for this to go in, but I think we should consider breaking this into smaller hooks.

2024-10-15 16:50 UTC, Cutaiar requested changes
👍 Nice work. Left some feedback, please reach out if you want to discuss anything.

2024-10-15 22:15 UTC, audreyostrom commented on src/components/profile/widgets/file-drop-area.tsx
> +      style={{ border: fileEnter ? '2px dashed #000' : 'none' }}
Oh yeah, that's on me! I actually haven't used Tailwind CSS very seriously prior to this, but that's good to know + a big learning area for me. Thank you for the suggestion, I'll run it by Chris first before merging this one in.

2024-10-17 18:32 UTC, audreyostrom commented on src/components/profile/widgets/file-drop-area.tsx
> +      style={{ border: fileEnter ? '2px dashed #000' : 'none' }}
Uploading Screen Recording 2024-10-17 at 11.28.44 AM.mov…

Here's a demo of what the animation looks like!

2024-10-17 22:09 UTC, Cutaiar approved these changes
See my slack comment and this is approved!

2024-10-21 17:10 UTC, merged