[SRBT-299] Profile Page Updates
MySorbet/sorbet-app pull request #122
Opened 2024-10-28 17:44 UTC by audreyostrom

# [SRBT-299] Profile Page Updates

**Changes**

- Image Cropping
- Link Redirection
- 
# Screenshots

Screenshots/videos of the changes made (if any, otherwise delete this section)

2024-11-05 19:18 UTC, ChristopherPark3 commented on src/api/widgets.ts
> +  let payload: any = {
I think the 'any' is unnecessary as you don't redefine it anywhere so it can even be a 'const'. Just something to note as well, try to avoid the `any` type as it can kind of hurt in the long run. I'm definitely guilty of it, and just wanted to point it out so you avoid the same mistakes I made :)

2024-11-05 19:22 UTC, ChristopherPark3 commented on src/api/widgets.ts
> +  } catch (error: any) {
Along the same note, the api calls are kind of weird to type as well. You can definitely find it somewhere in the code base, but I believe axios says to cast the error as `unknown`, and then run some conditionals to see if it is an `AxiosError` and go from there. If you look in `auth.ts`, there's a good example. (Ofc this is in the context of making a network call via axios)

![Screenshot 2024-11-05 at 11 21 13 AM](https://github.com/user-attachments/assets/7b42c730-7016-4ab7-a7b8-76e75ea9fb3c)

2024-11-05 19:27 UTC, ChristopherPark3 commented on src/components/profile/widgets/add-link.tsx
> +import React, { useState } from 'react';
One small thing, if you could go through and fix the imports to follow the ESLint rules that would be awesome. If you right click or press 'cmd+.', there should be an option to auto sort the imports. If you don't see the ESLint warnings then lmk and I can try to help you get that working!

2024-11-05 19:29 UTC, ChristopherPark3 commented on src/hooks/profile/useWidgetManagement.ts
> +      let widgetUrl: string = '';
Minor: ESLint is saying this cast to 'string' is unnecessary

2024-11-05 19:34 UTC, ChristopherPark3 commented on src/hooks/profile/useWidgetManagement.ts
> +        toast({
Oh and then here, I think we spoke about moving away from the shadcn toasts to the sonner toasts. Not a big deal in this PR, we can go through and change it in it's own separate PR. Just wanted to remind going forward (I get the old way was already implemented before you touched this file).

2024-11-05 19:43 UTC, ChristopherPark3 commented on src/hooks/profile/useWidgetManagement.ts
> +          await useUpdateWidgetImageAsync(newObj);
Minor: theres an error saying that you can't call hook inside of a hook. If you just get rid of 'use' in the name, it'll go away. useUpdateWidgetImageAsync -> updateWidgetImageAsync.

2024-11-05 19:44 UTC, ChristopherPark3 commented on src/hooks/profile/useWidgetManagement.ts
> +          await useUpdateWidgetImageAsync(newObj);
Love the thoughts of optimization!

2024-11-05 19:44 UTC, ChristopherPark3 approved these changes
Awesome stuff Audrey!

2024-11-06 16:43 UTC, audreyostrom commented on src/components/profile/widgets/add-link.tsx
> +import React, { useState } from 'react';
Sorry about that, I forgot to lint everything before I converted this to a PR.

2024-11-06 17:20 UTC, Cutaiar requested changes
This is just a quick sweep. Will take a more detailed look later today.

2024-11-06 17:20 UTC, Cutaiar commented on public/svg/section-title.svg
Adding a section title icon isn't needed for this PR correct?

2024-11-06 17:20 UTC, Cutaiar commented on src/api/widgets.ts
> +  } catch (error: any) {
In catch blocks, you can leave the error untyped. We have TS set up to interpret them as `unkown` automatically. Then you can do what chris says here to handle the error.

2024-11-06 17:20 UTC, Cutaiar commented on src/components/profile/widgets/add-link.tsx
> +  const { toast } = useToast();
Let's use [Sonner](https://ui.shadcn.com/docs/components/sonner) for toasts moving forward.

2024-11-06 17:20 UTC, Cutaiar commented on src/components/profile/widgets/widget-section.tsx
Weren't you excluding section title from this PR?

2024-11-06 17:20 UTC, Cutaiar commented on src/types/widgets.ts
> +  Section: { w: 4, h: 1 },
Similar to other comments, I though section titles was excluded from this PR?

2024-11-06 17:31 UTC, audreyostrom commented on src/api/widgets.ts
> +  let payload: any = {
Thank you@

2024-11-06 17:32 UTC, audreyostrom commented on src/components/profile/widgets/widget-section.tsx
Re: this and the other comments, I'll remove any reference to sections.

2024-11-07 19:31 UTC, Cutaiar commented
As discussed, we probably don't want to allow zoom cropping. So the scrolling when cropping should not have an effect. Images that are longer than they are tall should only be able to be moved horizontally. Images that are taller than they are long should only be able to be moved vertically. And square images should probably have cropping disabled. Like bento:

![CleanShot 2024-11-07 at 12 29 01@2x](https://github.com/user-attachments/assets/69877383-769a-47f9-bac3-aef78116c520)

Please make an account and play with bento.me to get an idea of their UX.

2024-11-07 19:35 UTC, Cutaiar commented
The location and size of link dropdown should match design:
![CleanShot 2024-11-07 at 12 34 46@2x](https://github.com/user-attachments/assets/d57c71ef-d831-439d-9d71-bf01a6f1b647)

design:

![CleanShot 2024-11-07 at 12 35 34@2x](https://github.com/user-attachments/assets/5e017968-a3bc-4e91-b4ab-40476116f03f)

2024-11-07 19:37 UTC, Cutaiar commented
When cropping, we don't need this grey background. Just the black border and image. (as per design and bento)

2024-11-07 19:39 UTC, Cutaiar commented
When cropping, clicking outside the widget should apply the cropping. As it stands, I couldn't figure out how to apply the cropping until i hovered the widget again and saw the green crop button.

2024-11-07 19:49 UTC, Cutaiar commented
Something in this PR makes it so that any change to a widget (uploading an image to a link widget, adding a new widget, etc) causes all the widgets to go into a loading state. This should not be the case. Updating or adding a widget should not effect the others visually.

2024-11-07 19:53 UTC, Cutaiar requested changes
Made some individual comments, and grouped some into a review here. Great work and a good start to this pretty large feature. It is coming along but needs some polish and aligment with design.

2024-11-07 19:53 UTC, Cutaiar commented on src/api/widgets.ts
> +  } catch (error: unknown) {
Same for the rest of the caught errors in this file

2024-11-07 19:53 UTC, Cutaiar commented on src/hooks/profile/useWidgetManagement.ts
> +          await updateWidgetLinkAsync(newObj);
Since all you are updating about the widget is it's link, I think it's more appropriate for for `updateWidgetLinkAsync` to just take the link (and widget id) as a param, rather requiring the caller to construct a whole widget object just to update the link. You can propgate this change all the way down. so `updateWidgetLink` from the api folder can get this change too.

Seems like the same change could apply to `updateWidgetImage` as well. Please consider this -- if it turns out its not cleaner, that's fine, but generally, functions should take as params only what they need.

2024-11-07 19:53 UTC, Cutaiar commented on src/hooks/profile/useWidgetManagement.ts
> +    [layout]
Eslint is complaining about this dep array. Are you getting these warnings?

2024-11-07 19:53 UTC, Cutaiar commented on src/components/ui/input.tsx
>              prefix && 'rounded-l-none',
Hm. Could you comment on what this line is doing? When would `noRing` be both `undefined` and `true`?

2024-11-07 19:53 UTC, Cutaiar commented on src/components/profile/widgets/widget.tsx
>    };
This todo should not be removed. I still beleive widgets should be anchors rather than divs, but this will take a some effort to solve.

2024-11-07 19:53 UTC, Cutaiar commented on src/api/widgets.ts
> +    }
Rather than repeating this in every catch block, you could consider extracting this logic to a function like `catchAndRethrowWidgetErrror(error: unkown, message?: string)` or something like this. that way, this code is less redundant, and upgrades to error handling can benefit all these functions.

2024-11-14 16:15 UTC, audreyostrom commented on src/components/ui/input.tsx
>              prefix && 'rounded-l-none',
That line has been more appropriately configured to make sense because you are right. I also just refactored it to be a variant as well since I apply similar styling on the Section Title branch.

2024-11-14 17:28 UTC, audreyostrom commented on src/hooks/profile/useWidgetManagement.ts
> +    [layout]
Yes, the ones relevant to this PR are fixed.

2024-11-14 17:45 UTC, audreyostrom commented on src/hooks/profile/useWidgetManagement.ts
> +          await updateWidgetLinkAsync(newObj);
I applied this change for widget link. For updateWidgetImage, I more aptly renamed it to to `updateWidgetContent` to account for the fact that the name for the image URL for all the widgetContentTypes isn't consistent (i.e. for photo widgets it's `image` and for links it's `heroImageUrl`)

2024-11-27 18:51 UTC, Cutaiar approved these changes

2024-12-04 21:40 UTC, Cutaiar commented on public/svg/empty-widget-background.svg
> +<svg width="260" height="180" viewBox="0 0 260 180" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Seems like this svg should be removed now.

2024-12-04 21:51 UTC, Cutaiar commented on src/components/profile/widgets/widget-photo.tsx
>        />
```suggestion
        style={isCropped && croppedArea ? calculateStyles(croppedArea) : undefined}
```

2024-12-04 21:52 UTC, Cutaiar commented on src/components/profile/widgets/widget-photo.tsx
> +
```suggestion
  const croppedArea = content.croppedArea;
  const isCropped = content.isCropped;
```

Doesn't look like this cast is needed

2024-12-04 21:54 UTC, Cutaiar commented on src/components/profile/widgets/modify-widget-image.tsx
> +export const ModifyImageWidget: React.FC<ModifyImageWidgetProps> = ({
A TSDoc comment describing what this component is would be nice. Also seems like a more appropriate name would be "ModifyImageControls". We already use the term widget for the components on the profile, best not to overload it.

2024-12-04 21:57 UTC, Cutaiar commented on src/components/profile/widgets/modify-widget-image.tsx
> +  width = 24,
You can use `className='size-5'` rather than exposing specific width and height props. This way it behaves like the other icons we use.

2024-12-04 22:00 UTC, Cutaiar commented on src/components/profile/widgets/cropping-widget.tsx
> +              : 'opacity-0 transition-opacity duration-300 hover:opacity-100'
```suggestion
          className={cn('absolute left-1/2 -translate-x-1/2 -translate-y-1/2 transform', isPopoverOpen && 'opacity-0 transition-opacity duration-300 hover:opacity-100')
```

2024-12-04 22:05 UTC, Cutaiar commented on src/components/profile/widgets/widget-behance.tsx
> +  removeImage: (key: string) => Promise<void>;
these and the other props you've added to every widget are pretty repetitive. Let's extract them to an interface like `BaseWidgetProps` and have each widget interface extend this interface. This way, you don't have to make changes to almost 20 files if you want to change that interface.

2024-12-04 22:08 UTC, Cutaiar commented on src/components/profile/widgets/widget-dribbble.tsx
> +                className='absolute left-1/2 top-0 z-20 flex -translate-x-1/2 -translate-y-1/2 transform items-center opacity-0 transition-opacity group-hover:opacity-100'
These classes are repeated on every `ModifyImageWidget`. If you wanted to tweak this, you'd have to change it in many files. Would be better to share these classes via a component which wraps `ModifyImageWidget` such as `ModifyImageWidgetWithHover` or something like that.

2024-12-04 22:09 UTC, Cutaiar commented on src/components/profile/widgets/widget-dribbble.tsx
> +                hasImage={content.image ? true : false}
```suggestion
                hasImage={Boolean(content.image)}
```
or
```suggestion
                hasImage={!!content.image}
```

2024-12-04 22:09 UTC, Cutaiar commented on src/components/profile/widgets/widget-dribbble.tsx
> +                hasImage={content.image ? true : false}
And the same for the rest of the places you render `ModifyImageWidget`

2024-12-04 22:21 UTC, Cutaiar commented on src/components/profile/widgets/widget.tsx
>        >
```suggestion
        onClick={!showControls ? onWidgetClick : undefined} // Don't redirect if editing dashboard, similar to Bento
```

2024-12-04 22:39 UTC, Cutaiar commented on src/components/profile/widgets/widget.tsx
> +                  popoverOpen={isPopoverOpen}
Is there a good reason that the open state of the add link input needs to be pulled all the way out to this component? 

If so, please give it a more descriptive name like `isAddLinkOpen` so that it is clear what the state is for. 

If not, seems that this state could be local to the `ResizeWidget` component.

2024-12-04 22:40 UTC, Cutaiar commented on src/components/profile/widgets/add-link.tsx
> +        // otherwise, update widget's link
Doesnt look like you are calling onsubmission here?

2024-12-04 22:44 UTC, Cutaiar commented on src/components/profile/widgets/add-link.tsx
> +  onSubmission,
The interface for this component is a little confusing. Rather than make it a controlled component component, I would let this component hold the state for the link value. Then when a submission happens, you have the onSubmission callback pass the newvalue to the parent. This way, you can remove the value and onChange props. And just have an onSubmit prop to communicate to the parent.

This helps because you should normalize the links that are passed to the parent anyway. DM me and I can help elucidate this more.

2024-12-06 20:23 UTC, audreyostrom commented on src/components/profile/widgets/modify-widget-image.tsx
> +      const validExtensions = ['jpg', 'jpeg', 'png', 'gif', 'svg'];
Sounds good. I moved this function to the `util.tsx` folder.

2024-12-06 20:24 UTC, audreyostrom commented on src/components/profile/widgets/widget-behance.tsx
> +  removeImage: (key: string) => Promise<void>;
Added BaseWidgetProps to `src/types/widget.ts` and added the appropriate extensions

2024-12-06 20:33 UTC, audreyostrom commented on src/components/profile/widgets/cropping-widget.tsx
> +              : 'opacity-0 transition-opacity duration-300 hover:opacity-100'
Removed all instances like this and replaced them with more appropriate `cn()` uses

2024-12-06 21:05 UTC, audreyostrom commented on src/components/profile/widgets/add-link.tsx
> +        // otherwise, update widget's link
Added back.

2024-12-06 21:11 UTC, audreyostrom commented on src/components/profile/widgets/widget.tsx
> +                  popoverOpen={isPopoverOpen}
Originally, this snippet on main was:

```
{showControls && (
          <div
            className={cn(
              'absolute bottom-0 left-1/2 -translate-x-1/2 transform opacity-0 transition-opacity duration-300 group-hover:opacity-100',
              type !== 'SectionTitle' && 'translate-y-5',
              type === 'SectionTitle' && '-translate-y-1' // to account for margins on the background of section titles
            )}
          >
            <div className='flex flex-row gap-1'>
              {type !== 'SectionTitle' && (
                <ResizeWidget
                  onResize={onWidgetResize}
                  initialSize={initialSize}
                />
              )}
              <Button
                variant='outline'
                size='icon'
                className='rounded-full border-gray-800 bg-gray-800 text-white hover:bg-gray-800 hover:text-white'
                onClick={(e) => {
                  e.stopPropagation();
                  handleRemove(identifier);
                }}
              >
                <Trash2 size={18} />
              </Button>
            </div>
          </div>
        )}
  ```
The reason why I moved this extra logic in `widget.tsx` is to ensure that the popover stays visible when editing a link. When the user starts typing in the input box while editing a link, they're technically no longer hovering over this  div containing the trash button on resize widget – making it disappear.

I renamed it to `isAddLinkOpen` as you suggested.

2024-12-06 21:37 UTC, audreyostrom commented on src/components/profile/widgets/widget-dribbble.tsx
> +                className='absolute left-1/2 top-0 z-20 flex -translate-x-1/2 -translate-y-1/2 transform items-center opacity-0 transition-opacity group-hover:opacity-100'
Reading it closely, all the strings are the same. I just moved this className into the component itself and there were no differences.

2024-12-09 17:35 UTC, Cutaiar commented on src/components/profile/widgets/modify-widget-image.tsx
> +export const ModifyImageControls: React.FC<ModifyImageControlsProps> = ({
file name should generally be the same as the main exported component, but in kebab case. So this would be `modify-image-controls.tsx`

2024-12-09 17:38 UTC, Cutaiar commented on src/components/profile/widgets/widget-dribbble.tsx
> +                className='absolute left-1/2 top-0 z-20 flex -translate-x-1/2 -translate-y-1/2 transform items-center opacity-0 transition-opacity group-hover:opacity-100'
It doesn't look like there was any change here. The idea with this comment is to reduce redundant code. This string is repeated 21 times. It would be better to write it once and apply it to `ModifyImageWidget` or a wrapping component.

2024-12-09 17:47 UTC, Cutaiar commented
Left two more comments. When they are resolved, go ahead and merge!

2024-12-09 17:53 UTC, audreyostrom commented on src/components/profile/widgets/widget-dribbble.tsx
> +                className='absolute left-1/2 top-0 z-20 flex -translate-x-1/2 -translate-y-1/2 transform items-center opacity-0 transition-opacity group-hover:opacity-100'
Sorry I thought you were just referring to the className string being repeated, which I removed from the numerous instances. Am I wrong?

2024-12-09 19:18 UTC, merged