[SRBT-362] Remove unintended animations after cropping finish
MySorbet/sorbet-app pull request #150
Opened 2024-12-16 17:54 UTC by audreyostrom

# [SRBT-362] Remove unintended animations after cropping finish

**Changes**

- To remove the widgets animating from (0,0) when cropping is finished, I've added `useCSSTransforms={false}` to ReactGridLayout as per this [issue](https://github.com/react-grid-layout/react-grid-layout/issues/103) for the library.

2024-12-16 23:35 UTC, Cutaiar approved these changes

2024-12-16 23:42 UTC, Cutaiar requested changes
Actually, I'm not sure this is the best way to achieve the desired effect?

```
// Uses CSS3 translate() instead of position top/left.
// This makes about 6x faster paint performance
useCSSTransforms: ?boolean = true,
```

From the docs on RGL, looks like this creates a 6x slowdown? I'm wondering why we get the 0,0 animation after crop but not on initial page load.

2024-12-17 17:32 UTC, audreyostrom commented
@Cutaiar I believe the animation might be due to the fact that I hide the react-grid-layout when cropping, and then unhide it. I believe there's some default stylings for that situation. I found a way to address this without using `useCSSTransforms` by finding the styling causing it and disabling it.

2024-12-18 00:05 UTC, Cutaiar commented
Awesome, please include some comments in that CSS to call out to future devs why we have that.

2024-12-18 00:07 UTC, Cutaiar approved these changes

2024-12-18 00:24 UTC, merged