U/cp/privy launch UI cleaning
MySorbet/sorbet-app pull request #60
Opened 2024-08-27 23:25 UTC by ChristopherPark3

# Description & Technical Solution]
- Fixes Avatar ui bug on `edit profile modal`
- Fixes broken tag input on `edit profile modal`
  - Does so by incorporating `Syntax UI` premade `tag-input` component
- Adjusts profile edit modal to match figma (border radius)
- Adds minor micro animation on hover of share button

# Screenshots

Provide screenshots or videos of the changes made if any (optional)

2024-08-28 19:05 UTC, Cutaiar requested changes

2024-08-28 21:15 UTC, ChristopherPark3 commented on src/components/common/skill-input.tsx
> +export const SkillInput = ({
This is the new component that is from Syntax UI

2024-08-28 21:16 UTC, ChristopherPark3 commented on src/components/onboarding/signup/step3.tsx
> +          )}
Ahh yea, that makes sense, I'll work on that part now

2024-08-28 21:29 UTC, ChristopherPark3 commented on src/components/profile/profile-header.tsx
> +                <Share06 className='h-5 w-5 transition ease-in-out group-hover:translate-x-[1px] group-hover:translate-y-[-0.5px] group-hover:rotate-6' />
I'm not so sure if it'll be reused because it was pretty specific to the share button and it's icon.

2024-08-28 21:32 UTC, ChristopherPark3 commented on src/components/onboarding/signup/step3.tsx
> +            <h3 className="text-[#344054]' text-sm font-normal">
Relocated the message to the skill-input component!

2024-08-28 21:38 UTC, ChristopherPark3 commented on src/components/profile/profile-edit-modal.tsx
> +  const [skills, setSkills] = useState<string[]>(user?.tags || []);
Got rid of the uneccessary state!

2024-08-29 16:11 UTC, Cutaiar commented on src/components/onboarding/signup/skill-badge.tsx
> +  removeSkill: MouseEventHandler<HTMLButtonElement>;
```suggestion
  onRemove: MouseEventHandler<HTMLButtonElement>;
```
More convential to use a var beginning with `on`. Then functions which handle this callback are called `handleRemove`.

https://react.dev/learn/responding-to-events#naming-event-handler-props

2024-08-29 16:16 UTC, Cutaiar commented on src/components/profile/profile-edit-modal.tsx
>          bio: data.bio,
```suggestion
        firstName: data.firstName,
        ...data
```

Since all of the names are the same, you can just destructure this. Also, a more descriptive name like `formData` would be good.

2024-08-29 16:19 UTC, Cutaiar commented on src/components/onboarding/signup/step3.tsx
> +  const isMaxSkills = userData.skills.length >= 5;
This is not needed now that the skill input controls this

2024-08-29 16:20 UTC, Cutaiar approved these changes

2024-08-29 17:48 UTC, ChristopherPark3 commented on src/components/profile/profile-edit-modal.tsx
>          bio: data.bio,
will do!

2024-08-29 19:24 UTC, merged