U/wb/wallet
MySorbet/sorbet-app pull request #67
Opened 2024-09-05 21:51 UTC by wonderboy25

# To do
-Show wallet balance on wallet page
-stop backend call for transaction

2024-09-06 23:35 UTC, Cutaiar requested changes
Great work, Olec. Thanks for your help here. Left some comments. Once addressed, this should be ready to go in!

Please do update the PR description with a title and a bulleted list of the changes. The description ends up being the merge commit so it is helpful to have good information about the change there.

2024-09-06 23:35 UTC, Cutaiar commented on src/app/wallet/wallet-container.tsx
> +  // const { user } = useAuth();
Remove commented code if you do not need it.

2024-09-06 23:35 UTC, Cutaiar commented on src/app/wallet/wallet-container.tsx
> +  // console.log('user', user);
Remove commented code if you do not need it.

2024-09-06 23:35 UTC, Cutaiar commented on src/app/wallet/wallet-container.tsx
> +              icon={<MoveUp size={16} />}
Please attach a screenshot to the PR so that we can see what this change looks like!

2024-09-06 23:35 UTC, Cutaiar commented on src/hooks/useWeb3React.tsx
A file containing a single exported hook should be named the same as the hook. Please call this file: `useWalletBalances.ts`. Also note, the `ts` extension rather than `tsx` since there is no JSX in this file.

2024-09-06 23:35 UTC, Cutaiar commented on src/hooks/useWeb3React.tsx
> +        if (!walletAddress) {
I assume this is to check for empty string (`''`). If so, you can be more descriptive and concise with:

```suggestion
        // Ignore empty string wallet address
        if (!walletAddress) return;
```

If you never expect this to be empty string and you are instead expecting and checking for `null` / `undefined`. Please type the hook parameter correctly: `(walletAddress?: string)`.

2024-09-06 23:35 UTC, Cutaiar commented on src/hooks/useWeb3React.tsx
> +    fetchBalances();
You can use an IIFE for this kind of effect to avoid naming a function you only call once.
https://developer.mozilla.org/en-US/docs/Glossary/IIFE#execute_an_async_function

2024-09-06 23:35 UTC, Cutaiar commented on src/lib/config.ts
> +  baseRpcUrl: process.env.NEXT_PUBLIC_BASE_RPC_URL,
Please pull latest main and merge it. You will see my [latest PR](https://github.com/MySorbet/sorbet-app/pull/68) changes this to an object called `env` which you should add this variable to.

2024-09-06 23:35 UTC, Cutaiar commented on src/app/wallet/wallet-container.tsx
> +      const wallet = getEmbeddedConnectedWallet(wallets);
Why do you have to use `getEmbeddedConnectedWallet`. Why can't you just use the first wallet from `useWallets`?

![CleanShot 2024-09-06 at 17 32 28@2x](https://github.com/user-attachments/assets/1fea504e-af4a-49df-9b29-a5f181acc23b)

2024-09-06 23:35 UTC, Cutaiar commented on src/app/wallet/wallet-container.tsx
> +  // const fetchTransactions = async (last_days = 30) => {
If you want to leave this commented code in, maybe add a `// TODO: Move transactions to base` above it or something like that? Want to avoid a codebase with dead code lying around.

2024-09-06 23:45 UTC, wonderboy25 commented on src/hooks/useWeb3React.tsx
I am going to make other hook methods related web3, so it is good to keep original file name

2024-09-06 23:47 UTC, wonderboy25 commented on src/app/wallet/wallet-container.tsx
> +              icon={<MoveUp size={16} />}
![Screenshot 2024-09-07 074620](https://github.com/user-attachments/assets/cb2d5cea-9230-403f-adb8-6006aade358a)

2024-09-06 23:47 UTC, wonderboy25 commented on src/app/wallet/wallet-container.tsx
> +              icon={<MoveUp size={16} />}
attached a screenshot

2024-09-06 23:50 UTC, wonderboy25 commented on src/app/wallet/wallet-container.tsx
> +      const wallet = getEmbeddedConnectedWallet(wallets);
I confirmed that first wallet can be different. In some cases, first address is shown as my injected address or sometimes it is shown as emebdded one.
Thus we have to use above function

2024-09-07 00:03 UTC, Cutaiar commented on src/hooks/useWeb3React.tsx
Ah in this case, please do you through with the name change, but put these new hooks in their own files with the same naming convention. To group them, you might consider putting them under `/hooks/web3/`?

2024-09-07 00:04 UTC, Cutaiar commented on src/app/wallet/wallet-container.tsx
> +      const wallet = getEmbeddedConnectedWallet(wallets);
Makes sense. Though I imagine there could be users who would prefer we use their injected address. We will have to look more into this later but this is fine for now.

2024-09-07 01:48 UTC, wonderboy25 commented
remake PR

2024-09-07 01:51 UTC, Cutaiar approved these changes

2024-09-07 01:52 UTC, merged